services:
  # Backend Service
  - type: web
    name: recipe-backend
    env: node
    plan: starter
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: recipe-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: recipe-frontend
          envVarKey: RENDER_EXTERNAL_URL
      - key: ALLOWED_ORIGINS
        fromService:
          type: web
          name: recipe-frontend
          envVarKey: RENDER_EXTERNAL_URL

  # Frontend Service
  - type: web
    name: recipe-frontend
    env: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: recipe-backend
          envVarKey: RENDER_EXTERNAL_URL

  # Database
  - type: pserv
    name: recipe-db
    plan: starter
    databaseName: recipeDB
    user: recipeuser
