# TEMPLATE - NOT TESTED
# This is a template configuration for production deployment
# Requires customization and testing before use

version: '3.8'

services:
  mongo-container:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - recipe-app-network
    environment:
      - MONGO_INITDB_DATABASE=recipeDB
    # Production: Don't expose MongoDB port externally
    expose:
      - "27017"

  backend-container:
    build:
      context: ../../../src/backend
      dockerfile: ../../../deployment/docker/production/backend.Dockerfile
    restart: unless-stopped
    depends_on:
      mongo-container:
        condition: service_healthy
    env_file:
      - env.production
    volumes:
      - uploads:/app/uploads
    networks:
      - recipe-app-network
    # Production: Don't expose backend port externally (use reverse proxy)
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend-container:
    build:
      context: ../../../src/frontend
      dockerfile: ../../../deployment/docker/production/frontend.Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    restart: unless-stopped
    depends_on:
      - backend-container
    networks:
      - recipe-app-network
    # Production: Don't expose frontend port externally (use reverse proxy)
    expose:
      - "3000"

  # Production: Add Nginx reverse proxy
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend-container
      - frontend-container
    networks:
      - recipe-app-network

networks:
  recipe-app-network:
    driver: bridge

volumes:
  mongo-data:
  uploads:
